### ISSUE TITLE
About geometry

### ISSUE THREAD

**Issue by nzatsepilov** [Nihlus/libwarcraft#10]
Have you any plans to implement extracting of ADT's geomerty? 
Such as https://goo.gl/SE78hB (BananaMpq's AdtBuilder)

**Comment by Nihlus** [comment]
This should already be completely possible in the library. It's more low-level than BananaMPQ, so building the actual logic for transforming the vertex data into something else would be up to you. 

However, if you have any suitable utility functions you think would simplify this if added to the ADT class, please create an issue for those and I'll do my best to add them :)

**Comment by nzatsepilov** [comment]
Thank you for feedback. 
Ok, i'll let you know about anything interesting.
